import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:ifind/features/business/domain/entities/business.dart';
import 'package:ifind/features/business/domain/repositories/business_repository.dart';
import 'package:ifind/features/business/presentation/providers/business_provider.dart';
import 'package:ifind/features/needs/data/repositories/needs_repository.dart';
import 'package:ifind/features/needs/domain/entities/need.dart';

final needsRepositoryProvider = Provider<NeedsRepository>((ref) {
  return NeedsRepository(Supabase.instance.client);
});

final myNeedsProvider = StreamProvider.family<List<Need>, String>((ref, userId) {
  return ref.watch(needsRepositoryProvider).watchMyNeeds(userId);
});

/*
  Controller for posting a need.
  Handles AI analysis and submission.
*/
class PostNeedState {
  final bool isAnalyzing;
  final bool isSubmitting;
  final Map<String, dynamic>? aiAnalysis;
  final List<Business> matchingBusinesses;
  final String? error;

  PostNeedState({
    this.isAnalyzing = false,
    this.isSubmitting = false,
    this.aiAnalysis,
    this.matchingBusinesses = const [],
    this.error,
  });

  PostNeedState copyWith({
    bool? isAnalyzing,
    bool? isSubmitting,
    Map<String, dynamic>? aiAnalysis,
    List<Business>? matchingBusinesses,
    String? error,
  }) {
    return PostNeedState(
      isAnalyzing: isAnalyzing ?? this.isAnalyzing,
      isSubmitting: isSubmitting ?? this.isSubmitting,
      aiAnalysis: aiAnalysis ?? this.aiAnalysis,
      matchingBusinesses: matchingBusinesses ?? this.matchingBusinesses,
      error: error, // Clear error if not provided (or manage explicitly)
    );
  }
}

class PostNeedController extends StateNotifier<PostNeedState> {
  final NeedsRepository _needsRepository;
  final BusinessRepository _businessRepository;

  PostNeedController(this._needsRepository, this._businessRepository) : super(PostNeedState());

  Future<void> analyzeText(String text) async {
    state = state.copyWith(isAnalyzing: true, error: null);
    try {
      // Mocking AI service call for now to ensure MVP speed
      // In real implementation: final result = await _aiService.analyzeNeed(text);
      await Future.delayed(const Duration(seconds: 2)); // Simulate AI thinking
      
      final result = _mockAiAnalysis(text);
      
      // Fetch matching businesses
      final category = _stringToBusinessCategory(result['category']);
      final businessesResult = await _businessRepository.getNearbyBusinesses(
        latitude: 0.3476,
        longitude: 32.5825,
        radiusKm: 20,
        category: category,
      );
      
      final businesses = businessesResult.getOrElse(() => []);

      state = state.copyWith(
        isAnalyzing: false, 
        aiAnalysis: result,
        matchingBusinesses: businesses,
      );
    } catch (e) {
      state = state.copyWith(isAnalyzing: false, error: e.toString());
    }
  }

  Map<String, dynamic> _mockAiAnalysis(String text) {
    if (text.toLowerCase().contains('cake') || text.toLowerCase().contains('food')) {
      return {'category': 'Food & Drink', 'urgency': 'Medium', 'tags': ['Bakery', 'Cake', 'Sweets']};
    } else if (text.toLowerCase().contains('plumber') || text.toLowerCase().contains('fix')) {
      return {'category': 'Home Services', 'urgency': 'High', 'tags': ['Plumbing', 'Repair']};
    } else {
      return {'category': 'General', 'urgency': 'Low', 'tags': ['General']};
    }
  }

  BusinessCategory _stringToBusinessCategory(String category) {
    if (category.contains('Food')) return BusinessCategory.food;
    if (category.contains('Service') || category.contains('Home')) return BusinessCategory.service;
    if (category.contains('Retail')) return BusinessCategory.retail;
    if (category.contains('Entertainment')) return BusinessCategory.entertainment;
    return BusinessCategory.other;
  }

  Future<bool> submitNeed({
    required String userId,
    required String title,
    required String description,
    required String category,
    required double lat,
    required double long,
  }) async {
    state = state.copyWith(isSubmitting: true, error: null);
    try {
      final need = Need(
        id: '', // DB will generate
        userId: userId,
        title: title,
        description: description,
        category: category,
        latitude: lat,
        longitude: long,
        status: NeedStatus.active,
        createdAt: DateTime.now(),
      );
      
      // We are not using the Need object directly because ID is auto-generated by DB
      await _needsRepository.createNeed(need);
      
      state = state.copyWith(isSubmitting: false);
      return true;
    } catch (e) {
      state = state.copyWith(isSubmitting: false, error: e.toString());
      return false;
    }
  }
}

final postNeedProvider = StateNotifierProvider<PostNeedController, PostNeedState>((ref) {
  return PostNeedController(
    ref.watch(needsRepositoryProvider),
    ref.watch(businessRepositoryProvider),
  );
});

final nearbyNeedsProvider = FutureProvider<List<Need>>((ref) async {
  final repository = ref.read(needsRepositoryProvider);
  // Hardcoded location for MVP, or use Geolocator
  return repository.getNearbyNeeds(0.3476, 32.5825, 10.0);
});

